server.port=8090
logging.level.web = debug

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

restClient.ai.url=http://localhost:8080/orch-ai
#restClient.keycloak.url=http://130.185.121.173:8081
restClient.keycloak.url=https://auth.simorq.top

xmpp.connection.host=130.185.121.173
xmpp.connection.port=5222
xmpp.connection.domainName=zchat.ir

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://130.185.121.173:5432/orchestrator
spring.datasource.username=x
spring.datasource.password=x

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.kafka.bootstrap-servers=x
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=orch-core
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.projectZ.orchestrator.infrastructure.adapter.in.broker.userEvent.EventDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.enable-auto-commit=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.simorq.top/realms/project-z
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://auth.simorq.top/realms/project-z/protocol/openid-connect/certs
jwt.auth.converter.resource-id: orchestrator-resource
jwt.auth.converter.principle-attribute: preferred_username

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc=DEBUG
