package io.projectZ.orchestrator.infrastructure.adapter.in.broker.dto;
/*
  Project : Openfire-Synchonorizer-provdier
  Author  : AmirHFF
  Created : 7/12/2026 - 11:24 PM
*/

public enum ProfileEventType {

    LOGIN,
    LOGIN_ERROR,
    REGISTER,
    REGISTER_ERROR,
    LOGOUT,
    LOGOUT_ERROR,

    CODE_TO_TOKEN,
    CODE_TO_TOKEN_ERROR,

    CLIENT_LOGIN,
    CLIENT_LOGIN_ERROR,

    REFRESH_TOKEN,
    VALIDATE_ACCESS_TOKEN,
    VALIDATE_ACCESS_TOKEN_ERROR,
    INTROSPECT_TOKEN,
    INTROSPECT_TOKEN_ERROR,

    FEDERATED_IDENTITY_LINK,
    FEDERATED_IDENTITY_LINK_ERROR,
    REMOVE_FEDERATED_IDENTITY,
    REMOVE_FEDERATED_IDENTITY_ERROR,


    UPDATE_EMAIL,
    UPDATE_EMAIL_ERROR,
    UPDATE_PROFILE,
    UPDATE_PROFILE_ERROR,

    UPDATE_PASSWORD,
    UPDATE_PASSWORD_ERROR,

    UPDATE_TOTP,
    UPDATE_TOTP_ERROR,
    VERIFY_EMAIL,
    VERIFY_EMAIL_ERROR,
    VERIFY_PROFILE,
    VERIFY_PROFILE_ERROR,

    REMOVE_TOTP,
    REMOVE_TOTP_ERROR,

    GRANT_CONSENT,
    GRANT_CONSENT_ERROR,
    UPDATE_CONSENT,
    UPDATE_CONSENT_ERROR,
    REVOKE_GRANT,
    REVOKE_GRANT_ERROR,

    SEND_VERIFY_EMAIL,
    SEND_VERIFY_EMAIL_ERROR,
    SEND_RESET_PASSWORD,
    SEND_RESET_PASSWORD_ERROR,
    SEND_IDENTITY_PROVIDER_LINK,
    SEND_IDENTITY_PROVIDER_LINK_ERROR,
    RESET_PASSWORD,
    RESET_PASSWORD_ERROR,

    RESTART_AUTHENTICATION,
    RESTART_AUTHENTICATION_ERROR,

    INVALID_SIGNATURE,
    INVALID_SIGNATURE_ERROR,
    REGISTER_NODE,
    REGISTER_NODE_ERROR,
    UNREGISTER_NODE,
    UNREGISTER_NODE_ERROR,

    USER_INFO_REQUEST,
    USER_INFO_REQUEST_ERROR,

    IDENTITY_PROVIDER_LINK_ACCOUNT,
    IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR,
    IDENTITY_PROVIDER_LOGIN,
    IDENTITY_PROVIDER_LOGIN_ERROR,
    IDENTITY_PROVIDER_FIRST_LOGIN,
    IDENTITY_PROVIDER_FIRST_LOGIN_ERROR,
    IDENTITY_PROVIDER_POST_LOGIN,
    IDENTITY_PROVIDER_POST_LOGIN_ERROR,
    IDENTITY_PROVIDER_RESPONSE,
    IDENTITY_PROVIDER_RESPONSE_ERROR,
    IDENTITY_PROVIDER_RETRIEVE_TOKEN,
    IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR,
    IMPERSONATE,
    IMPERSONATE_ERROR,
    CUSTOM_REQUIRED_ACTION,
    CUSTOM_REQUIRED_ACTION_ERROR,
    EXECUTE_ACTIONS,
    EXECUTE_ACTIONS_ERROR,
    EXECUTE_ACTION_TOKEN,
    EXECUTE_ACTION_TOKEN_ERROR,

    CLIENT_INFO,
    CLIENT_INFO_ERROR,
    CLIENT_REGISTER,
    CLIENT_REGISTER_ERROR,
    CLIENT_UPDATE,
    CLIENT_UPDATE_ERROR,
    CLIENT_DELETE,
    CLIENT_DELETE_ERROR,

    CLIENT_INITIATED_ACCOUNT_LINKING,
    CLIENT_INITIATED_ACCOUNT_LINKING_ERROR,
    TOKEN_EXCHANGE,
    TOKEN_EXCHANGE_ERROR,

    OAUTH2_DEVICE_AUTH,
    OAUTH2_DEVICE_AUTH_ERROR,
    OAUTH2_DEVICE_VERIFY_USER_CODE,
    OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR,
    OAUTH2_DEVICE_CODE_TO_TOKEN,
    OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR,

    AUTHREQID_TO_TOKEN,
    AUTHREQID_TO_TOKEN_ERROR,

    PERMISSION_TOKEN,
    PERMISSION_TOKEN_ERROR,

    DELETE_ACCOUNT,
    DELETE_ACCOUNT_ERROR,

    // PAR request.
    PUSHED_AUTHORIZATION_REQUEST,
    PUSHED_AUTHORIZATION_REQUEST_ERROR,
    USER_DISABLED_BY_PERMANENT_LOCKOUT,
    USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR,

    USER_DISABLED_BY_TEMPORARY_LOCKOUT,
    USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR,

    OAUTH2_EXTENSION_GRANT,
    OAUTH2_EXTENSION_GRANT_ERROR,

    FEDERATED_IDENTITY_OVERRIDE_LINK,
    FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR,

    UPDATE_CREDENTIAL,
    UPDATE_CREDENTIAL_ERROR,

    REMOVE_CREDENTIAL,
    REMOVE_CREDENTIAL_ERROR,

    INVITE_ORG,
    INVITE_ORG_ERROR,

    USER_SESSION_DELETED,
    USER_SESSION_DELETED_ERROR,

    VERIFIABLE_CREDENTIAL_REQUEST,
    VERIFIABLE_CREDENTIAL_REQUEST_ERROR,
    VERIFIABLE_CREDENTIAL_OFFER_REQUEST,
    VERIFIABLE_CREDENTIAL_OFFER_REQUEST_ERROR,
    VERIFIABLE_CREDENTIAL_NONCE_REQUEST,
    VERIFIABLE_CREDENTIAL_NONCE_REQUEST_ERROR,
    VERIFIABLE_CREDENTIAL_CREATE_OFFER,
    VERIFIABLE_CREDENTIAL_CREATE_OFFER_ERROR,
    VERIFIABLE_CREDENTIAL_PRE_AUTHORIZED_GRANT,
    JWT_AUTHORIZATION_GRANT,
    VERIFIABLE_CREDENTIAL_PRE_AUTHORIZED_GRANT_ERROR,
    JWT_AUTHORIZATION_GRANT_ERROR


}