server.port=8091
logging.level.web = debug

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


spring.ai.openai.base-url=https://api.gapgpt.app
spring.ai.openai.api-key=x

spring.ai.openai.chat.options.model=gapgpt-qwen-3.5

spring.ai.openai.chat.options.temperature=0.9
spring.ai.openai.chat.options.max-tokens=500

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://130.185.121.173:8081/realms/project-z
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://130.185.121.173:8081/realms/project-z/protocol/openid-connect/certs
jwt.auth.converter.resource-id: orchestrator-resource
jwt.auth.converter.principle-attribute: preferred_username


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://130.185.121.173:5432/orchestrator
spring.datasource.username=x
spring.datasource.password=x

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
